add_newline = true
format = """
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$character"""

[directory]
style = "blue bold"

[character]
success_symbol = "\\$"
error_symbol = "[\\$](red)"

[git_branch]
format = "(on [$branch]($style) )"
style = "purple bold"

[git_status]
format="([$conflicted$stashed$ahead_behind]($style) )"
conflicted = "✗"
stashed = "≡"
ahead = "${count}↑"
behind = "${count}↓"
diverged = "${ahead_count}↑ ${behind_count}↓"
style = "purple"

[python]
format = "(\\($virtualenv\\) )"
