[general]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x6F6E69"
blue = "0x205EA6"
cyan = "0x24837B"
green = "0x66800B"
magenta = "0xA02F6F"
red = "0xAF3029"
white = "0xF2F0E5"
yellow = "0xAD8301"

[colors.cursor]
cursor = "0x4d4d4c"
text = "0xffffff"

[colors.normal]
black = "0x100F0F"
blue = "0x205EA6"
cyan = "0x24837B"
green = "0x66800B"
magenta = "0xA02F6F"
red = "0xAF3029"
white = "0xFFFCF0"
yellow = "0xAD8301"

[colors.primary]
background = "0xFFFCF0"
foreground = "0x100F0F"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 5000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
dynamic_padding = false
opacity = 1.0
startup_mode = "Maximized"

[window.padding]
x = 8
y = 2
